[versions]
junit = "5.11.3"
assertj = "3.26.3"
mockito = "5.14.2"
wiremock = "3.9.2"
jackson = "2.18.1"
javalin = "6.3.0"
slf4j = "2.0.16"
postgresql = "42.7.4"
pgvector = "0.1.6"
testcontainers = "1.20.3"

[libraries]
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
wiremock = { module = "org.wiremock:wiremock", version.ref = "wiremock" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-yaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jackson" }
javalin = { module = "io.javalin:javalin", version.ref = "javalin" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
postgresql-driver = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
pgvector-jdbc = { module = "com.pgvector:pgvector", version.ref = "pgvector" }
testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
testcontainers-postgresql = { module = "org.testcontainers:postgresql", version.ref = "testcontainers" }
testcontainers-junit-jupiter = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }
